apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-infra.yml -n testing
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
  namespace: testing
spec:
  ports:
    - name: "29092"
      port: 29092
      targetPort: 29092
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "9101"
      port: 9101
      targetPort: 9101
  selector:
    io.kompose.service: broker
status:
  loadBalancer: {}
